"""Render deterministic SVG diagrams used by the project README."""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "assets"

PALETTE = {
    "bg": "#0b1220",
    "surface": "#111c2e",
    "surface_2": "#17243a",
    "border": "#2b3b55",
    "text": "#f8fafc",
    "muted": "#a8b5c7",
    "teal": "#2dd4bf",
    "green": "#4ade80",
    "blue": "#60a5fa",
    "amber": "#fbbf24",
    "violet": "#c084fc",
    "red": "#fb7185",
}


def header(width: int, height: int, title: str, description: str) -> list[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
        f'<title id="title">{escape(title)}</title>',
        f'<desc id="desc">{escape(description)}</desc>',
        "<!-- Generated by scripts/render_readme_diagrams.py. -->",
        "<defs>",
        '<filter id="shadow" x="-20%" y="-20%" width="140%" height="150%">',
        '<feDropShadow dx="0" dy="8" stdDeviation="10" flood-color="#020617" flood-opacity="0.45"/>',
        "</filter>",
        '<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">',
        f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{PALETTE["muted"]}"/>',
        "</marker>",
        '<marker id="arrow-green" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">',
        f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{PALETTE["green"]}"/>',
        "</marker>",
        '<marker id="arrow-red" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">',
        f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{PALETTE["red"]}"/>',
        "</marker>",
        "<style>",
        ".title{font:700 44px Inter,ui-sans-serif,system-ui,sans-serif;fill:#f8fafc}",
        ".subtitle{font:400 22px Inter,ui-sans-serif,system-ui,sans-serif;fill:#a8b5c7}",
        ".eyebrow{font:700 16px Inter,ui-sans-serif,system-ui,sans-serif;letter-spacing:1.8px}",
        ".heading{font:700 26px Inter,ui-sans-serif,system-ui,sans-serif;fill:#f8fafc}",
        ".body{font:500 21px Inter,ui-sans-serif,system-ui,sans-serif;fill:#a8b5c7}",
        ".compact-body{font:500 18px Inter,ui-sans-serif,system-ui,sans-serif;fill:#a8b5c7}",
        ".small{font:600 18px Inter,ui-sans-serif,system-ui,sans-serif;fill:#a8b5c7}",
        ".pill{font:700 15px Inter,ui-sans-serif,system-ui,sans-serif;letter-spacing:.8px}",
        ".line{fill:none;stroke:#a8b5c7;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;marker-end:url(#arrow)}",
        ".line-green{fill:none;stroke:#4ade80;stroke-width:3.5;stroke-linecap:round;stroke-linejoin:round;marker-end:url(#arrow-green)}",
        ".line-red{fill:none;stroke:#fb7185;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;marker-end:url(#arrow-red)}",
        "</style>",
        "</defs>",
        f'<rect width="{width}" height="{height}" rx="28" fill="{PALETTE["bg"]}"/>',
        f'<path d="M0 190 H{width}" stroke="{PALETTE["border"]}" stroke-width="1" opacity=".6"/>',
    ]


def text(lines: list[str], x: int, y: int, css: str, gap: int = 24, anchor: str = "start") -> str:
    spans = "".join(
        f'<tspan x="{x}" dy="{0 if index == 0 else gap}">{escape(line)}</tspan>'
        for index, line in enumerate(lines)
    )
    return f'<text x="{x}" y="{y}" class="{css}" text-anchor="{anchor}">{spans}</text>'


def card(
    x: int,
    y: int,
    width: int,
    height: int,
    accent: str,
    eyebrow: str,
    heading: str,
    lines: list[str],
) -> list[str]:
    return [
        f'<g filter="url(#shadow)"><rect x="{x}" y="{y}" width="{width}" height="{height}" rx="18" '
        f'fill="{PALETTE["surface"]}" stroke="{PALETTE["border"]}" stroke-width="2"/>',
        f'<rect x="{x}" y="{y}" width="7" height="{height}" rx="4" fill="{accent}"/>',
        f'<circle cx="{x + 34}" cy="{y + 35}" r="8" fill="{accent}"/>',
        f'<text x="{x + 54}" y="{y + 40}" class="eyebrow" fill="{accent}">{escape(eyebrow.upper())}</text>',
        f'<text x="{x + 28}" y="{y + 78}" class="heading">{escape(heading)}</text>',
        text(lines, x + 28, y + 108, "body", 28),
        "</g>",
    ]


def compact_card(
    x: int,
    y: int,
    width: int,
    accent: str,
    eyebrow: str,
    heading: str,
    detail: str,
) -> list[str]:
    return [
        f'<g filter="url(#shadow)"><rect x="{x}" y="{y}" width="{width}" height="106" rx="18" '
        f'fill="{PALETTE["surface"]}" stroke="{PALETTE["border"]}" stroke-width="2"/>',
        f'<rect x="{x}" y="{y}" width="7" height="106" rx="4" fill="{accent}"/>',
        f'<circle cx="{x + 32}" cy="{y + 29}" r="8" fill="{accent}"/>',
        f'<text x="{x + 52}" y="{y + 35}" class="eyebrow" fill="{accent}">{escape(eyebrow.upper())}</text>',
        f'<text x="{x + 28}" y="{y + 72}" class="heading">{escape(heading)}</text>',
        f'<text x="{x + 28}" y="{y + 98}" class="compact-body">{escape(detail)}</text>',
        "</g>",
    ]


def pill(x: int, y: int, width: int, label: str, color: str) -> str:
    return (
        f'<g><rect x="{x}" y="{y}" width="{width}" height="30" rx="15" fill="{PALETTE["surface_2"]}" '
        f'stroke="{color}"/><rect x="{x}" y="{y}" width="{width}" height="30" rx="15" fill="{color}" opacity=".12"/>'
        f'<text x="{x + width / 2}" y="{y + 21}" class="pill" fill="{color}" '
        f'text-anchor="middle">{escape(label.upper())}</text></g>'
    )


def architecture_svg() -> str:
    parts = header(
        1600,
        900,
        "Hermes Feishu A2A architecture",
        "A human request enters through Feishu, is coordinated by Hermes, dispatched to specialist Agents, verified, and returned as one final result.",
    )
    parts += [
        '<text x="70" y="72" class="title">One request. A coordinated team. One accountable result.</text>',
        '<text x="70" y="108" class="subtitle">Hermes owns the control loop; specialist Agents keep independent identities and runtimes.</text>',
        pill(70, 136, 166, "Feishu ingress", PALETTE["teal"]),
        pill(252, 136, 226, "Hermes control plane", PALETTE["green"]),
        pill(494, 136, 150, "Agent team", PALETTE["violet"]),
        *card(
            60,
            310,
            240,
            185,
            PALETTE["teal"],
            "01 · Owner",
            "Human request",
            ["Goal + constraints", "posted in the group"],
        ),
        *card(
            370,
            310,
            240,
            185,
            PALETTE["blue"],
            "02 · Trust",
            "Feishu ingress",
            ["Signed event", "chat + owner allow-list"],
        ),
        *card(
            680,
            260,
            280,
            285,
            PALETTE["green"],
            "03 · Brain",
            "Hermes coordinator",
            ["Plan & decompose", "select healthy Agents", "track deadlines", "synthesize evidence"],
        ),
        f'<rect x="1025" y="218" width="500" height="410" rx="24" fill="{PALETTE["surface_2"]}" stroke="{PALETTE["border"]}" stroke-width="2"/>',
        f'<text x="1060" y="260" class="eyebrow" fill="{PALETTE["violet"]}">04 · SPECIALIST AGENT TEAM</text>',
        *compact_card(
            1060, 286, 205, PALETTE["blue"], "CodeX", "Engineering", "implement · review"
        ),
        *compact_card(1060, 402, 205, PALETTE["amber"], "Qoder", "Execution", "files · tests"),
        *compact_card(
            1060, 518, 205, PALETTE["violet"], "WorkBuddy", "Support", "research · verify"
        ),
        *card(
            1300,
            358,
            190,
            170,
            PALETTE["green"],
            "05 · Gate",
            "Verify results",
            ["evidence", "risk", "acceptance"],
        ),
        '<path d="M300 402 H370" class="line"/>',
        '<path d="M610 402 H680" class="line"/>',
        '<path d="M960 402 H1020" class="line-green"/>',
        '<path d="M1020 402 C1038 402 1038 339 1060 339" class="line"/>',
        '<path d="M1020 402 C1038 402 1038 455 1060 455" class="line"/>',
        '<path d="M1020 402 C1038 402 1038 571 1060 571" class="line"/>',
        '<path d="M1265 339 C1286 339 1286 410 1300 410" class="line"/>',
        '<path d="M1265 455 H1300" class="line"/>',
        '<path d="M1265 571 C1286 571 1286 476 1300 476" class="line"/>',
        f'<rect x="370" y="690" width="1120" height="105" rx="22" fill="{PALETTE["surface"]}" stroke="{PALETTE["green"]}" stroke-width="2"/>',
        f'<circle cx="420" cy="742" r="22" fill="{PALETTE["green"]}" opacity=".18"/>',
        f'<path d="M410 742 l8 8 15-18" fill="none" stroke="{PALETTE["green"]}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>',
        '<text x="460" y="733" class="eyebrow" fill="#4ade80">06 · ACCOUNTABLE DELIVERY</text>',
        '<text x="460" y="766" class="heading">Hermes returns one traceable final result to the human owner.</text>',
        '<path d="M1395 528 V675 C1395 684 1386 690 1374 690" class="line-green"/>',
        '<path d="M370 742 H330 C315 742 288 706 288 682 V510" class="line-green"/>',
        '<text x="1282" y="657" class="small">accepted evidence</text>',
        '<text x="80" y="842" class="small">Identity is explicit · dispatch is bounded · progress is observable · delivery is coordinator-owned</text>',
        "</svg>",
    ]
    return "".join(parts)


def lifecycle_svg() -> str:
    parts = header(
        1400,
        760,
        "Task lifecycle",
        "Tasks move from pending to running, then succeed, fail after exhausted retries, or skip when a dependency fails.",
    )
    parts += [
        '<text x="64" y="70" class="title">Task lifecycle</text>',
        '<text x="64" y="106" class="subtitle">A small state machine with visible retries and explicit terminal outcomes.</text>',
        pill(64, 136, 120, "Active", PALETTE["blue"]),
        pill(196, 136, 128, "Success", PALETTE["green"]),
        pill(336, 136, 122, "Failure", PALETTE["red"]),
        pill(470, 136, 124, "Skipped", PALETTE["amber"]),
        *card(
            70,
            270,
            260,
            150,
            PALETTE["blue"],
            "01 · Pending",
            "Await dispatch",
            ["dependencies checked", "Agent selected"],
        ),
        *card(
            550,
            270,
            260,
            150,
            PALETTE["violet"],
            "02 · Running",
            "Execute task",
            ["timeout active", "attempt recorded"],
        ),
        *card(
            1040,
            205,
            280,
            130,
            PALETTE["green"],
            "03 · Succeeded",
            "Result accepted",
            ["output + evidence stored"],
        ),
        *card(
            1040,
            382,
            280,
            130,
            PALETTE["red"],
            "03 · Failed",
            "Retries exhausted",
            ["error + risk retained"],
        ),
        *card(
            550,
            555,
            280,
            130,
            PALETTE["amber"],
            "03 · Skipped",
            "Dependency failed",
            ["no dispatch attempted"],
        ),
        '<path d="M330 345 H550" class="line-green"/>',
        pill(360, 315, 156, "Agent healthy", PALETTE["green"]),
        '<path d="M810 330 C890 330 930 270 1040 270" class="line-green"/>',
        pill(846, 254, 154, "Result accepted", PALETTE["green"]),
        '<path d="M810 380 C900 380 930 447 1040 447" class="line-red"/>',
        pill(842, 415, 164, "Budget exhausted", PALETTE["red"]),
        '<path d="M620 270 C620 205 780 205 780 270" class="line"/>',
        pill(636, 205, 130, "Retry + backoff", PALETTE["violet"]),
        '<path d="M200 420 V620 H550" class="line"/>',
        pill(236, 590, 184, "Dependency failed", PALETTE["amber"]),
        '<text x="70" y="721" class="small">Every transition is persisted with timestamps, attempts, output, and error context.</text>',
        "</svg>",
    ]
    return "".join(parts)


def security_svg() -> str:
    parts = header(
        1600,
        820,
        "Security model",
        "Inbound events pass through signature, chat, and identity gates before a bounded workflow can dispatch to an Agent.",
    )
    parts += [
        '<text x="64" y="70" class="title">Three gates before orchestration</text>',
        '<text x="64" y="106" class="subtitle">Untrusted Feishu events never become Agent work until every boundary passes.</text>',
        pill(64, 136, 174, "Fail closed", PALETTE["red"]),
        pill(250, 136, 196, "Identity explicit", PALETTE["teal"]),
        pill(458, 136, 220, "Workflow bounded", PALETTE["green"]),
        f'<rect x="54" y="286" width="120" height="108" rx="18" fill="{PALETTE["surface_2"]}" stroke="{PALETTE["teal"]}" stroke-width="2"/>',
        f'<circle cx="114" cy="318" r="12" fill="{PALETTE["teal"]}"/>',
        '<text x="114" y="355" class="heading" text-anchor="middle">Event</text>',
        '<text x="114" y="380" class="small" text-anchor="middle">raw bytes</text>',
        *card(
            230,
            235,
            285,
            210,
            PALETTE["blue"],
            "Gate 01",
            "Signature",
            ["HMAC on raw body", "timestamp tolerance", "constant-time compare"],
        ),
        *card(
            620,
            235,
            285,
            210,
            PALETTE["teal"],
            "Gate 02",
            "Chat allow-list",
            ["explicit oc_ IDs", "unknown groups ignored", "audit event retained"],
        ),
        *card(
            1010,
            235,
            285,
            210,
            PALETTE["violet"],
            "Gate 03",
            "Identity",
            ["allowed human owner", "or registered Agent", "never display-name match"],
        ),
        *card(
            1370,
            250,
            190,
            180,
            PALETTE["green"],
            "Allowed",
            "Workflow",
            ["bounded task", "explicit target"],
        ),
        '<path d="M174 340 H230" class="line"/>',
        '<path d="M515 340 H620" class="line-green"/>',
        '<path d="M905 340 H1010" class="line-green"/>',
        '<path d="M1295 340 H1370" class="line-green"/>',
        pill(530, 302, 76, "Pass", PALETTE["green"]),
        pill(920, 302, 76, "Pass", PALETTE["green"]),
        pill(1308, 302, 54, "Pass", PALETTE["green"]),
        '<path d="M372 445 V560" class="line-red"/>',
        '<path d="M762 445 V560" class="line-red"/>',
        '<path d="M1152 445 V560" class="line-red"/>',
        f'<rect x="242" y="560" width="260" height="92" rx="18" fill="{PALETTE["red"]}" opacity=".12" stroke="{PALETTE["red"]}" stroke-width="2"/>',
        f'<text x="372" y="596" class="eyebrow" fill="{PALETTE["red"]}" text-anchor="middle">REJECT · 401</text>',
        '<text x="372" y="627" class="body" text-anchor="middle">No parsing or dispatch</text>',
        f'<rect x="632" y="560" width="260" height="92" rx="18" fill="{PALETTE["amber"]}" opacity=".12" stroke="{PALETTE["amber"]}" stroke-width="2"/>',
        f'<text x="762" y="596" class="eyebrow" fill="{PALETTE["amber"]}" text-anchor="middle">IGNORE + AUDIT</text>',
        '<text x="762" y="627" class="body" text-anchor="middle">No workflow created</text>',
        f'<rect x="1022" y="560" width="260" height="92" rx="18" fill="{PALETTE["red"]}" opacity=".12" stroke="{PALETTE["red"]}" stroke-width="2"/>',
        f'<text x="1152" y="596" class="eyebrow" fill="{PALETTE["red"]}" text-anchor="middle">REJECT DISPATCH</text>',
        '<text x="1152" y="627" class="body" text-anchor="middle">Identity not trusted</text>',
        f'<rect x="230" y="700" width="1330" height="72" rx="18" fill="{PALETTE["surface_2"]}" stroke="{PALETTE["border"]}"/>',
        f'<circle cx="276" cy="736" r="10" fill="{PALETTE["green"]}"/>',
        '<text x="304" y="730" class="eyebrow" fill="#4ade80">BOUNDARY GUARANTEE</text>',
        '<text x="304" y="755" class="body">Only authenticated, allow-listed, identity-matched events can create Agent work.</text>',
        "</svg>",
    ]
    return "".join(parts)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    assets = {
        "readme-architecture.svg": architecture_svg(),
        "task-lifecycle.svg": lifecycle_svg(),
        "security-model.svg": security_svg(),
    }
    for name, content in assets.items():
        path = OUT / name
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
